### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by Kevlaris**
Compatible with: https://github.com/Tau-ri-Dev/JSGMod-1.12.2/commit/70805a8694819b6ac1c514e501ee2e8da2193a2e

### CODE REVIEW

**Comment by MineDragonCZ** [comment]
There are some conflicts (probably because of not up-to-date version of your file)

**Comment by Kevlaris** [comment]
I'm aware of that. After reopening the request twice, I decided to wait until you give the greenlight. Are the files done from your end?

**Comment by MineDragonCZ** [comment]
I think that now yes. Sorry for problems. I didn't know that we will add more content, when I give you green light xd

**Comment by Kevlaris** [comment]
It's alright!

**Pull request closed without merging**
